import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import myImg from '../assets/images/my.png'
import { AnimatePresence, motion } from 'framer-motion'

export default function Home() {
  return (
    <div className='font-LeagueSpartan'>
      <Head>
        <title>Mahbubur Rahman</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <motion.main className={styles.main}
        Layout
        animate={{ opacity: 1, transition: { duration: 2 } }}
        initial={{ opacity: 0 }}
        exit={{ opacity: 0 }}>

        {/* header */}
        <div className='mb-5'>
          <Image src={myImg} alt="Picture of the author" width='200' />
        </div>
        <div className='text-center'>
          <h1 className='font-bold text-5xl'>Hi, I{"'"}m Mahbubur.</h1>
          <h3 className='font-bold text-3xl'>Full Stack Developer</h3>
        </div>

        {/* skills */}
        <div className='text-center'>
          <h3 className='font-bold text-3xl mt-10'>Skills</h3>
          <p className='text-2xl'>HTML, CSS, Bootstrap, Tailwind, SASS, JavaScript, React, Firebase, Python, Django, PostgreSQL</p>
        </div>

        {/* works */}
        <div className='text-center'>
          <h3 className='font-bold text-3xl mt-10'>Works</h3>
          <h3>under construction..............</h3>
        </div>
      </motion.main>

      {/* footer  */}
      <footer className={styles.footer}>
        ©️ Copyright by Mahbubur
      </footer>
    </div >
  )
}
